ALTER SESSION SET "_ORACLE_SCRIPT"=true;

DROP PROCEDURE XLS.XL_UPDATE_TABLE_FORMAT;

DROP VIEW XLS.VIEW_COLUMNS;
DROP VIEW XLS.VIEW_FORMATS;
DROP VIEW XLS.VIEW_HANDLERS;
DROP VIEW XLS.VIEW_OBJECTS;
DROP VIEW XLS.VIEW_QUERIES;
DROP VIEW XLS.VIEW_TRANSLATIONS;
DROP VIEW XLS.VIEW_WORKBOOKS;
DROP VIEW XLS.QUERIES;
DROP VIEW XLS.USERS;

DROP INDEX    XLS.IX_COLUMNS;
DROP INDEX    XLS.IX_FORMATS;
DROP INDEX    XLS.IX_HANDLERS;
DROP INDEX    XLS.IX_OBJECTS;
DROP INDEX    XLS.IX_TRANSLATIONS;
DROP INDEX    XLS.IX_WORKBOOKS;

DROP TRIGGER  XLS.TR_COLUMNS_ID;
DROP SEQUENCE XLS.SQ_COLUMNS_ID;
DROP TABLE    XLS.COLUMNS;

DROP TRIGGER  XLS.TR_FORMATS_ID;
DROP SEQUENCE XLS.SQ_FORMATS_ID;
DROP TABLE    XLS.FORMATS;

DROP TRIGGER  XLS.TR_HANDLERS_ID;
DROP SEQUENCE XLS.SQ_HANDLERS_ID;
DROP TABLE    XLS.HANDLERS;

DROP TRIGGER  XLS.TR_OBJECTS_ID;
DROP SEQUENCE XLS.SQ_OBJECTS_ID;
DROP TABLE    XLS.OBJECTS;

DROP TRIGGER  XLS.TR_TRANSLATIONS_ID;
DROP SEQUENCE XLS.SQ_TRANSLATIONS_ID;
DROP TABLE    XLS.TRANSLATIONS;

DROP TRIGGER  XLS.TR_WORKBOOKS_ID;
DROP SEQUENCE XLS.SQ_WORKBOOKS_ID;
DROP TABLE    XLS.WORKBOOKS;

DROP ROLE     XLS_DEVELOPERS;
DROP ROLE     XLS_FORMATS;
DROP ROLE     XLS_USERS;

DROP USER     XLS;

prompt SaveToDB Framework removed
